language: objective-c
osx_image: xcode11
xcode_workspace: A.xcworkspace
xcode_scheme: A
xcode_sdk: iphonesimulator

env:
  global:
    - echo "Getting version for cocoapods release"
    - RELEASE_VERSION=$(cat version.txt)


before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
before_script:
  - echo "Version is $RELEASE_VERSION"
  - echo $RELEASE_VERSION
